(function () {
  const gallery = slug => [`./assets/worlds/${slug}-1.webp`, `./assets/worlds/${slug}-2.webp`];

  const world = (name, eyebrow, intro, slug, gallery, moments, palette) => ({
    name, eyebrow, intro, palette, slug,
    photos: gallery,
    moments
  });

  const worlds = [
    world('The First Airport Hug', 'where distance finally loses',
      'The doors slide open and every rehearsed sentence disappears. There is only you, me, the dropped bag, and the kind of hug that makes a whole year of waiting leave the body at once.',
      'airport-hug', gallery('airport-hug'), [
      ['The last hour of waiting', 'I get there early because of course I do. I check the arrivals board like it might change its mind about you.', 1],
      ['The sighting', 'I find you in the crowd and forget how walking normally works. You smile, I laugh from pure disbelief, and the room becomes background.', 1],
      ['The hug', 'Bag hits the floor. Neither of us says anything useful for a while. Somebody probably films us. Let them.', 1],
      ['The first drive', 'You take the passenger seat like it was always yours. Same playlist, but louder now that you are actually in the car.', 1],
      ['The first ordinary hour', 'We buy nothing important at a shop near mine. Watching you pick out snacks feels like a scene I waited a year for.', 1],
      ['Putting your things down', 'Your bag opens in my room and suddenly it is our room. Your things on my shelf. I keep looking at them.', 1],
      ['The first night in', 'No plans, no restaurant, nowhere to be. Just the lamp on and both of us talking until neither of us makes sense.', 1],
    ]),
    world('Santorini in Lilac Light', 'white walls, lavender sky',
      'Whitewashed steps, a sea that never stops being blue, and a sunset that turns everything the colour of the inside of a shell. We move slowly here because there is nothing to be late for.',
      'santorini', gallery('santorini'), [
      ['Cliffside breakfast', 'Fruit, strong coffee, and the whole caldera doing its thing below us. You take a photo of the view. I take one of you.', 1],
      ['The blue domes', 'We walk the lanes until we find the ones from every postcard, and they are somehow better in person.', 1],
      ['The wandering hour', 'Narrow steps, cats asleep in doorways, no map open. We get pleasantly lost and call it exploring.', 1],
      ['A swim below the cliffs', 'The water is colder than it looks and you shriek about it. Ten minutes later you refuse to get out.', 1],
      ['A dress for sunset', 'You change into the one that catches the light. I run out of vocabulary and just look at you instead.', 1],
      ['Dinner above the water', 'A small table, too much food, and the sky going from gold to lilac behind your head.', 1],
      ['Midnight balcony', 'Everything quiet, one blanket between us, the sea black and moving somewhere down there.', 1],
    ]),
    world('Maldives, No Schedule', 'a room floating on water',
      'Our room sits on stilts above water so clear it hardly looks real. There is nothing to do here, which is the entire point, and we get very good at it.',
      'maldives', gallery('maldives'), [
      ['Water-villa morning', 'You open the door straight onto the sea. There are steps down from the deck and no reason not to use them.', 1],
      ['Breakfast in the water', 'Someone floats a tray of breakfast to us. It is ridiculous. We eat all of it.'],
      ['The slow swim', 'Warm water, no current, nowhere to swim to. We float and argue gently about nothing.'],
      ['Fish that ignore us', 'Snorkels on. A whole city of fish below carrying on with its day, entirely unbothered by us.'],
      ['Dinner on the sand', 'A table set right on the beach, lanterns pushed into the sand, waves close enough to hear between sentences.'],
      ['Stars with no city', 'No streetlights for a hundred miles. The sky is absurd. You go quiet, which is how I know it got you too.'],
      ['Last swim before the flight', 'One more, quickly, still in yesterday\'s clothes. We are late because of it and neither of us minds.'],
    ]),
    world('Paris After Midnight', 'the city when it whispers',
      'Not rushed Paris. Ours begins after dinner, when the streets shine from rain and the city becomes quiet enough for our footsteps to sound like part of the music.',
      'paris', gallery('paris'), [
      ['The tiny cafe', 'You choose the prettier pastry. I claim I only want one bite and immediately become a liar.'],
      ['A bridge at midnight', 'We stop halfway across because you want to look at the water. The city keeps going without us.'],
      ['The tower sparkles', 'On the hour it does the thing. You have seen it a hundred times online and still gasp. I love that about you.'],
      ['The bookshop still open', 'A yellow window at one in the morning. We go in for two minutes and stay for forty.'],
      ['Streets after rain', 'Everything doubled in the wet stone. You walk slower here without noticing you are doing it.'],
      ['Walking home', 'No taxi. We choose the long way on purpose and neither of us says why.'],
      ['The last métro we miss', 'It goes without us while we are still deciding. Good. Now the night has to keep going.'],
    ]),
    world('Kyoto Blossom Rain', 'petals in your hair',
      'Spring keeps letting go of pink petals around us. We walk beneath old trees, speak more quietly without deciding to, and keep finding small beautiful things tucked beside the path.',
      'kyoto', gallery('kyoto'), [
      ['Temple morning', 'We arrive before the crowds. Bells sound somewhere beyond the trees and your hand finds mine inside my coat pocket.'],
      ['The red gates', 'A tunnel of them going up the hill, further than either of us expects. We climb further than we meant to.'],
      ['Tea for two', 'We sit by a paper window while steam curls between us. You taste mine. I knew you would.'],
      ['Petal weather', 'A gust fills the path with blossoms. I brush one from your hair and leave the prettiest one there.'],
      ['The bamboo hour', 'Green light, wind in the tops, the sound of a place breathing. We stop talking for a while.'],
      ['Lantern evening', 'The lanes glow gold after dark. We walk slowly because the night deserves our full attention.'],
      ['River, last light', 'We sit on the bank with cold drinks and watch the light leave the water.'],
    ]),
    world('Zanzibar Barefoot Morning', 'salt, spice, and sunlight',
      'Warm water, warmer air, and a coast that runs on its own time. Everything smells faintly of cloves and the sea, and shoes stop being relevant almost immediately.',
      'zanzibar', gallery('zanzibar'), [
      ['Sunrise feet', 'The tide is far out. We walk on wet sand for what feels like a mile and the sun comes up the whole way.'],
      ['Stone Town doors', 'Carved wooden doors on every corner, each one older than both of us. You photograph nearly all of them.'],
      ['Spice market', 'You hold cardamom to my nose and I pretend to be an expert. We buy far too much of everything.'],
      ['The blue hour swim', 'Bath-warm water and nobody else in it. We stay in until our fingers go strange.'],
      ['Dhow at dusk', 'A wooden sail against an orange sky. We sit at the front and let the boat do the talking.'],
      ['Rooftop dinner', 'Grilled fish, lime, and the call to prayer drifting over the roofs while we eat.'],
      ['Night on the sand', 'Warm dark, no wind, the water still going in and out. We stay far later than we planned.'],
    ]),
    world('The Swiss Window Seat', 'mountains passing like cinema',
      'A slow red train, a window each, and the Alps unrolling outside like something rehearsed. Neither of us gets tired of it, which is the surprising part.',
      'switzerland', gallery('switzerland'), [
      ['Window-seat treaty', 'We agree to swap every twenty minutes. Neither of us honours it. It works out anyway.'],
      ['The first tunnel', 'Dark, then suddenly an entire valley. You make the same small sound every time and I wait for it.'],
      ['A small mountain town', 'We get off somewhere unplanned because it looked pretty. It is. We eat there.'],
      ['Lunch with a view', 'Bread, cheese, something warm, and a mountain doing nothing dramatic outside the window.'],
      ['The quiet carriage', 'You fall asleep on my shoulder somewhere after the lake. I do not move for forty minutes.'],
      ['Lake evening', 'Still water, mountains upside down in it, cold air that makes standing close a practical decision.'],
      ['Late arrival', 'A small station, our breath visible, and nowhere to be until tomorrow.'],
    ]),
    world('Bali Hidden Garden', 'green doors and flower baths',
      'Everything is green and quietly alive. Water runs somewhere behind the walls, flowers keep turning up in unlikely places, and afternoons here last longer than they should.',
      'bali', gallery('bali'), [
      ['Breakfast among leaves', 'Fruit we cannot identify, coffee we can, and the jungle doing its enormous green thing on all sides.'],
      ['The flower bath', 'Petals across the whole surface. You are delighted. I take the photo you pretend not to want.'],
      ['The rice terraces', 'Steps of green going down a whole hillside. We walk them badly, in the wrong shoes, laughing.'],
      ['Scooter road', 'Your arms around me, palm shadows flicking past, both of us going far too slowly to be cool.'],
      ['The water temple', 'Cold spring water and something serious in the air. We stop being loud without discussing it.'],
      ['Rain on the roof', 'It arrives all at once, the way it does here. We stay put and let it be loud.'],
      ['Fireflies after dinner', 'The garden fills with small moving lights. You whisper for no reason. So do I.'],
    ]),
    world('Cappadocia Before Sunrise', 'balloons above the quiet',
      'We get up in the dark for this, and it is worth every minute of the alarm. The valley fills with colour and then with balloons, and nobody speaks above a murmur.',
      'cappadocia', gallery('cappadocia'), [
      ['The 4:30 alarm', 'You threaten violence. You get up anyway. Ten minutes later you are the one hurrying me.'],
      ['The valley in the dark', 'Cold air, strange rock shapes, and the sky only just beginning to think about it.'],
      ['The sky fills', 'First one, then ten, then more than we can count. You hold my arm without looking away.'],
      ['Our own basket', 'Off the ground before we are ready. You go completely silent, which from you means everything.'],
      ['Breakfast after wonder', 'Eggs, olives, bread, and neither of us able to fully stop grinning about what we just saw.'],
      ['Cave-room nap', 'Thick stone walls, cool dark, the whole day still ahead. We sleep for two hours and regret nothing.'],
      ['Sunset on the rocks', 'Back out for the other end of the day, the whole valley going orange and pink.'],
    ]),
    world('Venice After Rain', 'reflections under every bridge',
      'The rain stops just as we arrive and the whole city turns into a mirror. Every bridge doubles, every lamp doubles, and getting lost stops being a problem to solve.',
      'venice', gallery('venice'), [
      ['One shared umbrella', 'It is too small for two people. We use it anyway and both get half wet.'],
      ['Getting beautifully lost', 'The map gives up. We turn down whichever alley looks better and it always does.'],
      ['Coffee standing up', 'Like the locals, at a counter, quickly, for a fraction of the price. You approve of this system.'],
      ['A quiet gondola', 'Touristy and we do not care. Under a low bridge you go quiet and hold my hand tighter.'],
      ['The square at dusk', 'Pigeons, orchestras competing from opposite cafes, and the light going pink on the water.'],
      ['Tiramisu verdict', 'We try it in three places to be scientific. You have strong opinions. I write them down.'],
      ['Last vaporetto', 'The city sliding past on the water, cold air, your head on my shoulder.'],
    ]),
    world('Nairobi and Diani, Our Kenya Date', 'candlelight in Nairobi, bare feet in Diani',
      'Home ground, done properly. A city evening that feels like an occasion, then a coast where nothing is required of us at all.',
      'kenya', gallery('kenya'), [
      ['Candlelit Nairobi', 'A table booked for a Tuesday for no reason. You in that dress, and me forgetting most of my sentences.'],
      ['The road to Diani', 'Windows down, playlist loud, the landscape changing from town to green to salt air.'],
      ['First sight of the water', 'That specific blue that does not photograph properly. You stop walking when you see it.'],
      ['Two loungers, one view', 'Books we do not read, drinks that sweat in the heat, hours that stop counting themselves.'],
      ['Fresh fish, no cutlery', 'Grilled that morning, eaten with our hands at a plastic table. Best meal of the trip and we both know it.'],
      ['Barefoot after sunset', 'Warm sand, cold water at the ankles, and the two of us walking much further than intended.'],
      ['Night drive back', 'Windows down again, quieter now, your hand on my knee and nobody saying much.'],
    ]),
    world('Seychelles Secret Cove', 'granite, lilies, clear water',
      'Enormous smooth boulders, water you can see straight through, and a beach that appears to have been left off every map on purpose.',
      'seychelles', gallery('seychelles'), [
      ['The hidden path', 'A gap in the trees somebody told us about. Ten minutes of scrambling and then nobody else at all.'],
      ['The granite boulders', 'Huge, warm from the sun, shaped like something poured rather than placed.'],
      ['A private picnic', 'Bread, cheese, mangoes, and sand in absolutely everything by the end of it.'],
      ['Water like glass', 'You can count your toes in three feet of it. We stand around in the shallows for an hour.'],
      ['Reading beside you', 'Two books, no talking, your foot against mine. Somehow one of my favourite hours.'],
      ['Last swim', 'The light goes gold and we go back in for one more, because leaving felt premature.'],
      ['The walk back in the dark', 'Phone torch, warm air, your hand because the path is uneven and also because.'],
    ]),
    world('London Bookshop Rain', 'stories, tea, and your hand',
      'Grey outside and warm inside. We duck into places to get out of the rain and end up staying much longer than the weather requires.',
      'london', gallery('london'), [
      ['The note in the book', 'I hide one for you on a shelf in the poetry section. You find it faster than I planned.'],
      ['Second-hand stacks', 'Towers of them, no discernible system, and the specific smell of old paper you like.'],
      ['Afternoon tea', 'Tiny sandwiches we make fun of and then finish entirely. You take the last scone. Fair enough.'],
      ['Museum wandering', 'Big quiet rooms, whispered opinions about paintings, and a bench we sit on for far too long.'],
      ['The rain gets serious', 'We give up on the plan and stand in a doorway watching it come down.'],
      ['A pub with a fire', 'Corner table, something warm, coats steaming gently. Nowhere better to be.'],
      ['Rainy bus window', 'Top deck, front seats, the whole city sliding past behind water on the glass.'],
    ]),
    world('Rome at Golden Hour', 'warm stone and slow evenings',
      'Everything here is the colour of honey by six in the evening. Old stone, small streets, and a city entirely unbothered by being this beautiful.',
      'rome', gallery('rome'), [
      ['Morning espresso', 'Standing at the bar, one shot, thirty seconds, out again. You take to this immediately.'],
      ['A coin and a wish', 'Over the shoulder, eyes shut. You will not tell me what you wished for. I have theories.'],
      ['Ruins at noon', 'Two thousand years of stone and you asking better questions than the guide answers.'],
      ['Pasta lesson', 'Flour everywhere, dough behaving badly, and you laughing at my technique for a solid ten minutes.'],
      ['Gelato, second one', 'We said one. We are on our second. We will probably have a third.'],
      ['Steps after sunset', 'We sit on warm stone with everyone else and watch the sky do the pink thing over the roofs.'],
      ['The long way to dinner', 'Through three piazzas we did not need to cross, because you wanted to keep walking.'],
    ]),
    world('Northern Lights Cabin', 'the sky learning magic',
      'A small wooden cabin, snow to the windows, and a sky that might do something extraordinary tonight. We keep checking. It keeps making us wait.',
      'aurora', gallery('aurora'), [
      ['Cabin afternoon', 'Firewood, thick socks, and the light already going at three in the afternoon.'],
      ['Snow walk', 'Blue light, absolute silence, and the crunch of two sets of boots.'],
      ['The waiting game', 'Hot drinks, one eye on the window, checking a forecast neither of us understands.'],
      ['The first green ribbon', 'You see it before me and grab my arm hard enough to hurt. Worth it.'],
      ['Under one blanket', 'Outside, freezing, refusing to go in while the sky is still doing that.'],
      ['Firelight after', 'Back inside, faces cold, hands wrapped around mugs, both slightly stunned.'],
      ['Morning, all white', 'Snow on everything, sun low and pink on it, and nowhere at all we need to be.'],
    ]),
    world('Marrakech Lantern Night', 'rose walls and amber light',
      'Pink walls all day and amber light all evening. The city is loud in the best way, and our courtyard is completely silent the second the door shuts.',
      'marrakech', gallery('marrakech'), [
      ['Courtyard morning', 'Mint tea, tiled floor, a fountain going quietly, and the whole city locked outside the door.'],
      ['The souk', 'Narrow, crowded, gorgeous, overwhelming. You navigate it better than I do.'],
      ['Choosing a keepsake', 'One lamp, forty minutes of deliberation, and a negotiation you conduct with total confidence.'],
      ['The blue garden', 'Cool, green, unreasonably photogenic. We slow right down inside it.'],
      ['Rooftop sunset', 'The whole pink city going gold, swifts everywhere, and the call to prayer starting up across it.'],
      ['Lantern dinner', 'Amber light through cut metal, food that keeps arriving, and no interest in leaving.'],
      ['The square at night', 'Smoke, music, a hundred things happening at once. We hold hands so as not to lose each other.'],
    ]),
    world('Amalfi Lemon Afternoon', 'sunlight the color of joy',
      'Cliffs going straight into blue water, lemons the size of your hand, and a coast road that makes you gasp on every second corner.',
      'amalfi', gallery('amalfi'), [
      ['The coastal drive', 'Hairpins, sheer drops, and you leaning across me to see the water each time.'],
      ['The town from above', 'Stacked pastel houses going down to a small harbour. It looks invented.'],
      ['Lemon garden lunch', 'Pasta, lemonade, shade, and a long meal that resets a whole nervous system.'],
      ['The swimming stairs', 'Down a hundred steps to a tiny platform on the rocks. Cold, deep, perfect water.'],
      ['A boat for an hour', 'Out past the cliffs where the water goes properly dark blue, engine off, just floating.'],
      ['Balcony music', 'Someone practising somewhere below, badly, sweetly, while the light goes orange on the water.'],
      ['Limoncello, cold', 'Tiny glasses, far too sweet, and both of us pretending we are used to it.'],
    ]),
    world('Our Tiny Kitchen', 'the destination called ordinary',
      'The one I actually want most. Not a view, not a flight, just a small kitchen with both of us in it and nowhere either of us has to be.',
      'kitchen', gallery('kitchen'), [
      ['Sleepy coffee', 'You, half awake, holding the mug with both hands. I have wanted this exact scene for a long time.'],
      ['The grocery run', 'Arguing about which pasta shape while blocking an entire aisle. Domestic and perfect.'],
      ['Dinner experiment', 'We follow the recipe loosely and it goes fine. You taste-test everything. Quality control.'],
      ['Music between chores', 'Something on the speaker, you dancing badly at the sink, me pretending not to watch.'],
      ['Eating on the floor', 'The table is covered in something else. The floor works. It always does.'],
      ['The refrigerator evidence', 'Photos, a bad drawing, one note you left on a Tuesday that I never took down.'],
      ['Washing up, badly', 'You wash, I dry, one of us keeps flicking water. It takes twice as long as it should.'],
    ]),
    world('The Sunday Bedroom Fort', 'rain outside, us inside',
      'Rain on the window, nothing in the calendar, and a fort constructed with unnecessary seriousness. The whole day happens within about four square metres.',
      'bedroom-fort', gallery('bedroom-fort'), [
      ['Fort construction', 'Every blanket in the house is now structural. You are in charge. I am labour.'],
      ['Rain on the window', 'Grey light, water running down the glass, and absolutely nowhere to be.'],
      ['The snack delivery', 'Two trips because I am ambitious. Crumbs immediately become a permanent feature.'],
      ['A movie we barely watch', 'Twenty minutes in, we are talking over it. Neither of us knows how it ends.'],
      ['The nap that happens', 'Not planned. Grey light, warm blankets, both of us out for an hour and a half.'],
      ['Small talk, big topics', 'It starts about nothing and ends somewhere serious, the way it does when there is time.'],
      ['Falling asleep nearby', 'Lights off, rain still going, your breathing slowing down before mine does.'],
    ]),
    world('Twenty-Fifth of February', 'our date, made into a place',
      'Not a country. A date, turned into somewhere we can walk around. Everything in here is built out of the day the whole thing started.',
      'anniversary', gallery('anniversary'), [
      ['The anniversary garden', 'Everything planted on one date and still going. It gets bigger every year without asking us.'],
      ['Letters at noon', 'We read what we wrote a year ago. Some of it is embarrassing. All of it is true.'],
      ['The same song', 'The one from that week. It has not improved. It never had to.'],
      ['A cake, no occasion', 'Well, one occasion. Candles anyway, in the afternoon, for no good reason.'],
      ['The photo we retake', 'Same pose, different year, both of us slightly different. We keep every version.'],
      ['Counting out loud', 'Days, months, the number of times we nearly gave up and did not. The last number is zero.'],
      ['The next-year wish', 'One each, said out loud, written down, and put somewhere for next February.'],
    ]),
  ];

  const poems = [
    ["Instructions for Missing Me", "Free verse", `When the room becomes too large,\ndo not argue with the ache.\nGive it a chair.\nLet it sit beside you.\n\nPut one hand where your heartbeat\nkeeps doing its faithful little work.\nThat rhythm has crossed every mile\nwithout asking permission.\n\nOpen the window if the night is gentle.\nSay my name once, quietly.\nNot because distance is magic,\nbut because love is a kind of listening.\n\nThen breathe in for four.\nHold for the length of one forehead kiss.\nBreathe out until your shoulders remember\nthey were never meant to carry everything.\n\nI am not in the room, my love,\nbut I have left tenderness everywhere:\nin this page, in tomorrow,\nin the next hello already walking toward you.`],
    ["Sonnet for an Ordinary Morning", "Fourteen-line sonnet", `I do not only want the postcard view,\nthe ocean suite, the lanterns, or the flight.\nI want the kettle waking next to you,\nyour sleepy protest at the morning light.\n\nI want the shopping list upon the door,\nthe socks that somehow wander from their pair,\nthe question of what we are eating for\na dinner made more slowly because you are there.\n\nLet other poems ask the stars to move.\nMy grandest dream is smaller, warm, and near:\na thousand common mornings used to prove\nthat home is simply any place you appear.\n\nIf forever needs a shape that I can see,\nlet it be breakfast, you across from me.`],
    ["Villanelle for the Miles Between", "Villanelle", `The miles can count themselves; I will count you.\nThe calls, the laughs, the nights we did not leave.\nNo map has ever known what love can do.\n\nThe evening joins us, lilac and blue,\nand every quiet hour asks me to believe.\nThe miles can count themselves; I will count you.\n\nA screen goes dark, but what we said stays true.\nI keep your sweetness close, my babyy, and breathe.\nNo map has ever known what love can do.\n\nI build our future out of things we knew:\nyour voice, my name, the tenderness we weave.\nThe miles can count themselves; I will count you.\n\nOne day an airport door will let us through,\nand I will hold the girl I never want to leave.\nNo map has ever known what love can do.\n\nUntil that day, when missing fills the view,\nremember how completely I choose you and believe.\nThe miles can count themselves; I will count you.\nNo map has ever known what love can do.`],
    ["Moonpie, in Five Small Rooms", "Sequence", `I. THE CALL\nYour hello opens a door\nand I walk through smiling,\nalready happier because it is you.\n\nII. THE LAUGH\nA bright thing escapes you.\nMy whole day turns its face\ntoward the girl I love.\n\nIII. THE SILENCE\nNeither of us speaks.\nStill, I feel close to you,\nmy babyy resting beside my heart.\n\nIV. THE GOODNIGHT\nWe stretch one minute\nuntil it almost becomes forever,\nbecause neither of us wants to leave.\n\nV. THE MORNING\nI wake and find you\nalready waiting in my first thought,\nmy sweetest habit, my Moonpie.`],
    ["Prose Poem with a Kitchen Light", "Prose poem", `One day there will be a kitchen light we forget to turn off. It will spill under the doorway while we lie in bed discussing something that could have waited until morning. There will be two cups in the sink, one chair holding your clothes, music paused halfway through a song, and no airport between us. I will know which silence means you are tired and which means come closer. You will know I am listening even when I am searching for the right words. Nothing about the room will look miraculous to anyone else. That will be the miracle. Love will have stopped visiting and started living there.`],
    ["A Ghazal of Your Name", "Ghazal-inspired couplets", `Every soft place in me answers to your name.\nEven the moon turns when the night says your name.\n\nI have tried calling distance a temporary thing,\nbut my hands become impatient and write your name.\n\nThe future sends postcards with no return address:\na kitchen, an airport, a door marked with your name.\n\nIf sorrow arrives, let it find us holding steady.\nThere is shelter in the loving way I say your name.\n\nMy babyy, if the whole sky asks what prayer I repeat:\nonly you, only my Moonpie, only Michelle, your name.`],
    ["Twenty-Fifth", "Anniversary poem", `February kept one day\nand wrapped it gently in lilac.\n\nThe twenty-fifth arrived\nwith ordinary hours,\nyet somehow every clock\nlearned the shape of us.\n\nNow I carry that date\nlike a pressed pink flower:\ndelicate and beautiful,\nstrong enough to survive\nevery page that follows.\n\nYears from now\nI want to open the calendar,\nfind our small number waiting,\nand kiss my beautiful girl\nnot through a screen,\nnot through a wish,\nbut in the warm, lived-in air\nof the life we kept choosing.`],
    ["Lily Theology", "Lyrical ode", `I think lilies know something\nabout becoming visible.\n\nThey begin as a closed sentence,\na green promise held tightly,\nthen loosen one pale petal\nafter another\nuntil the whole room understands.\n\nThat is how I have loved you.\nNot all at once, perhaps,\nbut more honestly each day.\n\nA new tenderness opening.\nA new future showing its color.\nA new part of me saying,\nhere, take the light I was saving.\n\nIf I could send you a field,\nevery lily would lean your way.`],
    ["After the Call Ends", "Blank verse", `The room returns too quickly after us.\nA little screen goes dark. The walls remember\nthey are only walls. I hear the quiet\ncollecting all the places you had filled.\n\nBut love is not the call. It is the warmth\nthat stays behind, the sentence I replay,\nthe way I carry your unfinished laugh\ninto the next small duty of my day.\n\nI miss you, yes. I will not make it small.\nYet missing is not emptiness alone.\nIt is the outline made by something present,\nthe proof my heart has learned another home.`],
    ["The Future Uses Your Voice", "Love letter poem", `When I imagine tomorrow,\nit does not arrive silently.\n\nIt sounds like you\ncalling for me from another room,\nand me answering too quickly\nbecause I still love hearing that you need me.\n\nIt sounds like music on a Sunday,\nwater running in the kitchen,\nyour laugh interrupting my complaint,\nmy name made sweeter by your sleepy voice.\n\nI thought music was my favorite sound.\nThen I heard you, babyy.\nNow every future room I dream of\nis waiting to be filled with your voice.`],
    ["Small Astronomy", "Constellation poem", `There are stars we see\nlong after their light begins traveling.\n\nPerhaps love is also this:\nsomething bright crossing distance,\narriving faithfully\nafter the moment that made it.\n\nSo when a message from me\nfinds you late at night,\nknow it began earlier:\nin a thought while walking,\nin a smile at my phone,\nin the sudden wish\nto tell you everything.\n\nYou are not waiting in darkness.\nYou are standing where my light arrives.`],
    ["Birthday Benediction", "Blessing", `May this year be gentle with your softness\nand generous with your beautiful heart.\n\nMay doors open without making you beg.\nMay rest find you before exhaustion does.\nMay every mirror tell the truth:\nyou are gorgeous, precious, and deeply loved.\n\nMay your dreams become addresses,\nkeys, tickets, mornings,\nand photographs of us that we can touch.\n\nMay you never mistake a difficult day\nfor a difficult life.\nMay you always know exactly where my love is,\nwrapped around you, calling you babyy.\n\nAnd when the candles become smoke,\nmay the wish you keep secret\nalready be running toward you,\njust as I am.`]
  ];

  const extraLetters = [
    { title: "For the Day You Feel Too Much", tab: "open when it all spills over", theme: "safe", preview: "A full letter for the moments when your feelings arrive faster than words.", salutation: "My sweet girl,", body: [
      "If today made everything feel too close to the surface, you do not have to tidy yourself before coming to me. You do not need a perfect explanation. You can arrive confused, tired, quiet, tearful, clingy, or angry. I would rather meet the honest version of your heart than a polished version that had to suffer alone.",
      "Feelings are not evidence that you are difficult to love. They are messages from a part of you asking to be noticed. Sometimes the message is I am tired. Sometimes it is I need reassurance. Sometimes it is simply please stay near me while this passes. None of those requests make you too much.",
      "I may not always know the exact sentence that fixes the moment. I do know how I want to respond. I want to listen before defending, understand before solving, and make room before asking you to become smaller. Love should not punish honesty.",
      "So breathe, Moonpie. Tell me one piece at a time. If words will not come, send me a dot, a heart, a voice note with silence in it. I will know you are reaching. I will reach back.",
      "You are allowed to have weather. I am not only here for your sunny days."
    ], closing: "Come as you are. I love the whole sky." },
    { title: "What I Mean When I Say Forever", tab: "not a dramatic word", theme: "kitchen", preview: "Forever translated into groceries, patience, repair, and ordinary choosing.", salutation: "Moonpie,", body: [
      "When I say forever, I do not mean one endless romantic moment. I mean thousands of changing moments, some beautiful, some boring, some difficult, and the decision to keep treating what we have as precious inside all of them.",
      "I mean learning how you need to be spoken to when you are hurt. I mean apologizing without trying to win. I mean remembering what makes your mornings easier, which food comforts you, when you need advice, and when advice is the last thing you want.",
      "I mean practical love. Flights booked. Calls returned. Plans made. Promises supported by calendars and effort. I want our love to have hands and feet, not only beautiful sentences.",
      "I also mean laughter in the middle of responsibility. Dancing while dinner cooks. Sending you a ridiculous picture from the next room. Keeping our private language alive even when life gets busy.",
      "Forever is not something I expect time to build for us. It is something I want to build with you, one honest day at a time."
    ], closing: "My favorite long-term plan is still you." },
    { title: "For Your Quiet Achievements", tab: "I saw that too", theme: "stars", preview: "For the wins nobody clapped for loudly enough.", salutation: "My brilliant girl,", body: [
      "I want to celebrate the things that do not come with certificates. The day you got up even though your heart felt heavy. The conversation you handled with more grace than anyone noticed. The boundary you tried to set. The task you finished while carrying ten invisible thoughts.",
      "I notice growth that does not photograph well. You pause where you once reacted. You keep going where you once doubted yourself. You choose softness without surrendering your strength. Those changes matter.",
      "Please do not wait for the world to announce that you are becoming someone remarkable. You already are. Progress is often quiet because it is happening inside the rooms where only you know how hard the work was.",
      "I am proud of your ambition, but I am also proud of your survival, your tenderness, your rest, and every small return to yourself.",
      "Tonight, let one achievement be enough. You do not have to turn your whole life around before you deserve to feel proud."
    ], closing: "I am clapping for the parts nobody saw." },
    { title: "Read This After an Argument", tab: "us before pride", theme: "voice", preview: "A promise to choose repair without pretending hurt never happened.", salutation: "My love,", body: [
      "If we have hurt each other, I do not want this letter to rush you past what you feel. Love is not pretending everything is fine because conflict is uncomfortable. Your hurt deserves to be understood, and mine deserves words that do not become weapons.",
      "What I want us to remember is that the problem is not automatically you and it is not automatically me. Often it is a misunderstanding, a fear, a tired moment, or an unmet need standing between us and making itself look bigger than our care.",
      "I want to come back when we are calmer. I want to say what I meant, hear what landed, apologize for what was careless, and change more than the wording. Repair should leave evidence.",
      "Even when I need space, I do not want space to feel like abandonment. Even when I disagree, I do not want disagreement to make you question whether you are loved.",
      "We can be imperfect and still be safe with each other. We can learn. We can return."
    ], closing: "I choose understanding over winning." },
    { title: "The Home I Want to Make with You", tab: "a room-by-room promise", theme: "lilies", preview: "Not only a house. A feeling built carefully around both of us.", salutation: "My future home,", body: [
      "I want our home to feel like exhaling. Not perfect, not always tidy, not untouched by stress, but safe enough that neither of us has to perform calmness to deserve kindness.",
      "I want flowers somewhere, even if they are in an old jar. I want photographs that are slightly crooked because we hung them ourselves. I want a kitchen that knows our late-night snacks and a couch that has learned the shape of us sitting too close.",
      "I want your dreams to have room there. A corner for your work, shelves for what you love, silence when you need it, music when you do not. I do not want you to fit inside my life. I want us to make a life that fits both of us.",
      "On difficult days, I want the door to mean you made it back to someone who is on your side. On ordinary days, I want us to notice how lucky ordinary has become.",
      "The address will matter less than the way we treat each other inside it."
    ], closing: "Where you are loved gently, there is home." },
    { title: "A Letter from Our Future", tab: "postmarked someday", theme: "airport", preview: "Written as if the waiting ended and future-us sent something back.", salutation: "Dear younger us,", body: [
      "You were right to keep going. I know some nights made the distance feel permanent. It was not. I am writing from the kitchen you kept imagining. Michelle is in the next room, humming without realizing it. There are two mugs on the counter.",
      "The airport hug was messier than planned. Someone cried first and neither of you remembers who. The first week together felt both new and strangely familiar, like stepping into a room you had visited in dreams.",
      "Not everything became easy. Real life brought schedules, misunderstandings, tiredness, and decisions. But you learned that closeness is not the absence of difficulty. It is having someone beside you while you face it.",
      "You still call her Moonpie. She still makes that little protest when you have to leave the room at the wrong moment. The ordinary life you wanted is here, and it is even better because you remember what it cost to reach.",
      "So make the next call. Send the honest message. Book what can be booked. Keep building the bridge."
    ], closing: "With love from the life you did not give up on." }
  ];

  const notices = [
    "How your voice becomes softer when you are almost asleep but still do not want the call to end.",
    "How beautiful, cute, sexy, hot, and completely amazing you are.",
    "How your real laugh arrives in layers and makes me feel like I have won the entire day.",
    "The tiny protest in your voice when I say I have to go. I hear the love inside it.",
    "How you remember details people mention once and make them feel quietly important later.",
    "The way your face changes when music reaches the exact part you were waiting for.",
    "How you can be soft without being weak, and strong without making softness disappear.",
    "The brave way you keep caring even after life has given you reasons to guard yourself.",
    "How your silence has different meanings, and how I keep wanting to learn each one correctly.",
    "The way you say my name when you miss me, when you are amused, and when you need reassurance. They are three different songs.",
    "How you try to make other people comfortable, even when you are the one who needs tenderness.",
    "The specific warmth you bring into a conversation just by deciding to stay a little longer.",
    "How your beautiful mind can turn one little thought into a whole universe, and how I love being invited into it.",
    "The softness hidden inside your stubbornness. You hold on hard to what matters.",
    "How you make future plans sound less like fantasy and more like directions we can follow.",
    "The way you listen for what I mean, not only what I manage to say.",
    "The pause before you say something vulnerable, as if your heart checks the room before stepping out.",
    "The way tiredness makes you honest and somehow even more precious to me.",
    "How you care in practical ways: checking, remembering, asking, returning.",
    "The little shift in your energy when something is wrong, even before you give it words.",
    "How you deserve flowers on ordinary days, not only dates printed in bold on a calendar.",
    "The way your joy makes me want to protect the moment without interrupting it.",
    "How you can turn a normal call into the part of the day I remember most.",
    "The questions you ask when you are genuinely curious, and the focus in your voice while you listen.",
    "How you keep pieces of our conversations and bring them back when I thought they had floated away.",
    "The version of you that needs extra reassurance. I do not love her less. I want to hold her closer.",
    "How I always want to remind you that you are the most amazing and most beautiful girl in this whole 12,756-kilometre-wide world.",
    "How you are smart, really funny, really cute, and simply the best person to be with.",
    "How even your complaints can become part of our private comedy.",
    "The fact that your presence makes waiting rooms, traffic, and quiet evenings feel like shared life.",
    "How you keep growing without becoming unrecognizable to the tender person you have always been.",
    "The way you deserve to be chosen clearly, not left guessing at the edges of someone's effort.",
    "How your birthday feels important to me because the world had to make you before I could love you.",
    "The expressions I have not seen in person yet and already cannot wait to memorize.",
    "How your hand will fit inside mine for the first time and somehow feel remembered.",
    "The calm that sometimes arrives simply because your name appeared on my screen.",
    "How you are allowed to change your mind, take your time, and still be worthy of patient love.",
    "The way your dreams deserve logistics, support, calendars, and somebody asking how they can help.",
    "How I still find new things to notice, which means loving you has no boring final chapter.",
    "You, without comparison. There is nobody else I am trying to turn you into."
  ];

  const reasons = [
    "Your real laugh changes the temperature of my whole day.", "You make ordinary conversations feel worth remembering.", "Your kindness is practical, not performative.", "You listen for what I mean, not only what I say.", "Your sleepy voice feels like being trusted.",
    "You keep choosing softness without surrendering your strength.", "You remember tiny details and return them as care.", "Your eyes become gentler when you are happy.", "You make me want to speak more honestly.", "You can make a screen feel briefly like a room we share.",
    "You are curious in a way that makes the world feel larger.", "You care about doing things well because your heart is sincere.", "You have a quiet resilience that deserves more credit.", "Your sense of humor finds light without denying what is hard.", "You make future plans sound possible.",
    "You let me see the unpolished parts of you.", "You make reassurance feel like a language worth learning.", "Your stubbornness protects the things you love.", "You are beautiful when you forget anyone might be looking.", "You make my name sound different from everyone else.",
    "You bring warmth into places without asking for attention.", "You are thoughtful about people who may never know how much thought you gave them.", "You make me want to build, not only promise.", "You can be playful and profound inside the same conversation.", "You make silence feel accompanied.",
    "Your birthday matters because it began every version of you I get to love.", "You make distance feel temporary even when it is painful.", "You are not afraid to dream beyond what is immediately available.", "You keep growing while remaining tender.", "You have a voice I could recognize in any room.",
    "You make me look forward to ordinary mornings.", "You are worth planning flights, dates, and futures around.", "You make care feel specific instead of vague.", "You challenge me to become gentler and clearer.", "You deserve flowers, and loving you makes me want to keep bringing them.",
    "You make late nights feel shorter.", "You have survived things without letting them define every room in you.", "You know how to make small joy feel important.", "You make me want to celebrate your quiet wins.", "You are still yourself in a world that keeps asking people to perform.",
    "You make home feel like a person before it becomes a place.", "You trust me with feelings that deserve careful hands.", "You can make one hello repair a difficult hour.", "You make me curious about the life we have not lived yet.", "You are the person I want to tell good news first.",
    "You are also the person I want beside me when the news is hard.", "You make tenderness feel brave.", "You make me understand why people write letters.", "You are worth slowing down for.", "You make my imagination keep building rooms with two cups in them.",
    "You have a softness that is yours, not something the world gave permission for.", "You make me want to remember dates and details correctly.", "You can be clingy with me; I love being wanted by you.", "You make affection feel natural, not rehearsed.", "You are honest in the moments that matter.",
    "You make me want to repair quickly instead of protecting my pride.", "You have dreams I want to support with real effort.", "You make laughter show up in serious days.", "You make me want photographs and also moments too good to interrupt for one.", "You carry love in your questions.",
    "You make the future kitchen feel as exciting as any island.", "You deserve to wake without wondering whether you are chosen.", "You make my phone feel less like a device and more like a doorway.", "You have expressions I cannot wait to learn in person.", "You make me want to hold a hug longer than socially reasonable.",
    "You are patient with the process of us.", "You make waiting difficult because the destination matters so much.", "You have a way of becoming my first thought without trying.", "You make goodnight feel like a promise to return.", "You care even when you are tired.",
    "You notice when my energy changes too.", "You make mutual understanding feel possible.", "You can be dramatic with me; I love the evidence that you care.", "You make me want to protect joy, not control it.", "You are allowed to need, and I want to be someone safe to need.",
    "You make ordinary language fail in interesting ways.", "You are the reason Moonpie became my favorite word.", "You make anniversaries feel like little countries we invented.", "You deserve a love with follow-through.", "You make me want to turn paragraphs into plane tickets.",
    "You can change your mind and still remain deeply lovable.", "You make me want to ask better questions.", "You have a heart worth understanding slowly.", "You make distance reveal how much presence matters.", "You turn missing into proof that something beautiful is here.",
    "You make me want to know your routines, not only your highlights.", "You are someone I want beside me while doing separate things.", "You make sharing food, blankets, and time sound sacred.", "You deserve to be loved on the days you do not feel impressive.", "You make me want to bring calm, not confusion.",
    "You are not interchangeable with anybody.", "You make me want to be proud of us in public and careful with us in private.", "You have a future I want to witness up close.", "You make me believe a long distance can still lead somewhere real.", "You are my favorite person to imagine coming home to.",
    "You make love feel like attention.", "You make attention feel like devotion.", "You make devotion feel like daily practice.", "You are the person this whole little universe was built to hold.", "You are you, and that remains the reason underneath every other reason."
  ];

  const memories = [
    ["The first safe feeling", "It was not dramatic. I simply noticed that I could speak without arranging every sentence first. Something in me unclenched around you, and I wanted to stay there."],
    ["The calls that ran late", "We kept finding one more thing to say. Neither of us wanted to be responsible for ending the small room our voices had made."],
    ["The little protests", "That soft no when I have to go carries more tenderness than a perfect speech. It tells me my presence has weight in your day."],
    ["The future conversations", "We speak about kitchens, flights, mornings, and visits with enough detail that the future already has furniture."],
    ["The private language", "Moonpie. Princess. Babyy. Small names that became doors into a place only we know how to enter."],
    ["The first difficult honesty", "The moment we stopped trying to look effortless and chose truth instead. Love became less polished and more real."],
    ["The reassurance loops", "The times one of us needed to hear the same thing again. Repetition did not make the love less true; it made patience visible."],
    ["Songs becoming ours", "A track starts as someone else's music, then one late call changes it. Now the first notes carry a whole room back to me."],
    ["The sleepy goodnights", "Words becoming slower, voices becoming softer, both of us stretching the ending because tomorrow felt too far away."],
    ["The screenshots I keep", "Tiny pieces of conversation that would look ordinary to anyone else. To me they are evidence of us becoming us."],
    ["The day 2502 became a key", "A date became more than numbers. It became a way back into our story, a small code that says this belongs to us."],
    ["The first imagined airport", "Before any ticket, we had already pictured the doors, the searching crowd, and the hug. Hope rehearsed the scene for us."],
    ["The ordinary check-ins", "Did you eat? Are you home? How are you really? Love wearing practical clothes and showing up without needing applause."],
    ["The moments you stayed", "Not every important memory is a grand event. Some are simply the times leaving would have been easier and you stayed present."],
    ["This little universe", "A collection of code, flowers, words, and impossible intentions, all trying to become one simple thing: somewhere you can feel my care when I am far away."]
  ];

  const handMessages = [
    ["I felt you reach for me.", "Keep holding. Match the slow pulse under your thumb. For this minute, there is nowhere else you need to be."],
    ["Come closer, Moonpie.", "Imagine my palm against yours and my other hand around your shoulders. Let your jaw soften. I am listening."],
    ["You do not have to explain yet.", "Hold first. Breathe first. Words can arrive after your body remembers it is safe to be cared for."],
    ["Here is the truth, clearly.", "I love you. I am not disappearing. A quiet phone is not an empty heart. You are still held in my day."],
    ["Borrow my calm.", "Inhale slowly. Keep the air for one second. Exhale like you are setting down something heavy in my hands."],
    ["The distance did not win today.", "You reached across it and found me here. Every reach is part of the bridge we are building."],
    ["Stay for three heartbeats.", "One for where we began. One for where we are. One for the room where I finally get to hold your actual hand."],
    ["Nothing is required from you now.", "No brave face, no perfect reply, no immediate solution. Just be loved for a minute."],
    ["I would choose your hand in every crowd.", "At the airport, on a street, under a blanket, in our kitchen. My hand will keep learning where yours is."],
    ["You found the hidden hug.", "This is the part where I pull you in, kiss your forehead, and wait until your breathing changes."],
    ["I am on your side.", "Even when the day is confusing, even when we need to talk, even when feelings are messy. I want us against the problem."],
    ["One day this will not be pretend.", "You will reach sideways and find me. Until then, I will keep leaving pieces of my hand in places like this."]
  ];

  const songs = [
    ["Best Part", "Daniel Caesar feat. H.E.R.", "Because you are exactly that: the part my day keeps waiting for.", "1RMJOxR6GRPsBHL8qeC2ux"],
    ["Until I Found You", "Stephen Sanchez", "Big, old-fashioned devotion for the days subtlety is not invited.", "0T5iIrXA4p5GsubkhuBIKV"],
    ["Those Eyes", "New West", "For tiny gestures, private jokes, and the ordinary ways love proves itself.", "2psRActEWsTlYYd7EDoyVR"],
    ["Japanese Denim", "Daniel Caesar", "Warm silence, late calls, and the wish for more time in the same room.", "1boXOL0ua7N2iCOUVI1p9F"],
    ["Melting", "Kali Uchis", "For being dramatically, helplessly soft about you.", "2kSb3wYSOV996xA2NSmpck"],
    ["Still With You", "Jungkook", "A rainy-window song for presence that survives being apart.", "0eFMbKCRw8KByXyWBw8WO7"]
  ];

  const twentyWorlds = worlds.filter(item => item.name !== "New York Winter Lights");
  window.MOONPIE_EXPANSION = { worlds: twentyWorlds, poems, extraLetters, notices, reasons, memories, handMessages, songs };
})();
